const quizData = [
  {
    question: 'Which language runs in a web browser?',
    a: 'Java',
    b: 'C',
    c: 'Python',
    d: 'JavaScript',
    correct: 'd',
  },
  {
    question: 'What does CSS stand for?',
    a: 'Central Style Sheets',
    b: 'Cascading Style Sheets',
    c: 'Cascading Simple Sheets',
    d: 'Cars SUVs Sailboats',
    correct: 'b',
  },
  {
    question: 'What does HTML stand for?',
    a: 'Hypertext Markup Language',
    b: 'Hypertext Markdown Language',
    c: 'Hyperloop Machine Language',
    d: 'Helicopters Terminals Motorboats Lamborghinis',
    correct: 'a',
  },
  {
    question: 'Which of the following is a programming language?',
    a: 'HTML',
    b: 'CSS',
    c: 'JavaScript',
    d: 'SQL',
    correct: 'c',
  },
  {
    question: 'What does HTTP stand for?',
    a: 'Hypertext Transfer Protocol',
    b: 'Hyperloop Transport Protocol',
    c: 'High Transfer Protocol',
    d: 'Hypertext Transport Protocol',
    correct: 'a',
  },
  {
    question: 'What does SQL stand for?',
    a: 'Structured Query Language',
    b: 'Stylish Question Language',
    c: 'Statement Question Language',
    d: 'Structured Quick Language',
    correct: 'a',
  },
  {
    question: 'Which of the following is a JavaScript library?',
    a: 'React',
    b: 'Laravel',
    c: 'Django',
    d: 'Ruby on Rails',
    correct: 'a',
  },
  {
    question: 'Which year was JavaScript created?',
    a: '1995',
    b: '1996',
    c: '1997',
    d: '1998',
    correct: 'a',
  },
  {
    question: 'Who developed the Linux kernel?',
    a: 'Bill Gates',
    b: 'Linus Torvalds',
    c: 'Steve Jobs',
    d: 'Dennis Ritchie',
    correct: 'b',
  },
  {
    question: 'What is the main language used for Android development?',
    a: 'Swift',
    b: 'Kotlin',
    c: 'Objective-C',
    d: 'Python',
    correct: 'b',
  },
];

export default quizData;
